# Generated by Django 4.1 on 2023-02-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("native", "0012_bmi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("image", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                ("fb_account", models.CharField(max_length=200, unique=True)),
                ("youtube_account", models.CharField(max_length=200, unique=True)),
                ("insta_account", models.CharField(max_length=200, unique=True)),
                ("twitter_account", models.CharField(max_length=200, unique=True)),
                ("trainer_email", models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
